# Generated by Django 4.2.2 on 2023-06-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_credential_email_credential_gender_credential_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Credential",
        ),
    ]
