# Generated by Django 4.2.2 on 2023-06-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_delete_credential"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField()),
            ],
        ),
    ]
