# Generated by Django 4.2.2 on 2023-06-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_credential"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Credential",
        ),
    ]
