# Generated by Django 4.2.2 on 2023-06-11 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0006_delete_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
